# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'KeychainSwift'
    pod 'CryptoSwift' , '1.0.0'
    pod 'SwiftyBeaver'

end

target 'Appcircle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  
  pod 'GoogleMaps'
  pod 'PagingMenuController'
  pod 'SwiftyGif'
  pod 'Charts'
  pod 'SDWebImage', '5.10.0'
  pod 'Fabric'
  pod 'Firebase/Core', '~> 10.4.0'
  pod 'Firebase/Messaging', '~> 10.4.0'
  pod 'MaterialTextField', '~> 0.2.1'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'PPBlinkID', '~> 5.20.1'
  pod 'Firebase/Analytics', '~> 10.4.0'
  pod 'Firebase/DynamicLinks', '~> 10.4.0'
  pod 'Firebase/RemoteConfig', '~> 10.4.0'
  pod 'GoogleTagManager'
  pod 'AppDynamicsAgent'
  pod 'AppsFlyerFramework',
    :git => 'https://github.com/AppsFlyerSDK/AppsFlyerFramework'
  pod 'MFSDKHybridKit', '2.7.43'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'lottie-ios', '3.5.0'
  
  # Flutter sdk Pods
  #pod 'Flutter', :podspec => '../appcircle-sample-ios/FlutterSDK/Debug/Flutter.podspec' # This pod is for Debug version
  pod 'Flutter', :podspec => '../appcircle-sample-ios/FlutterSDK/Release/Flutter.podspec' # This pod is for Release version

  target 'AppcircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppcircleUITests' do
    # Pods for testing
  end

  post_install do |installer|
        installer.generated_projects.each do |project|
              project.targets.each do |target|
                  target.build_configurations.each do |config|
                      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                   end
              end
       end
    end
  
end
