# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

def shared_pods
    
    pod 'Alamofire', '4.9.1'
    pod 'SwiftyJSON', '5.0.2'
    pod 'KeychainSwift', '24.0.0'
    pod 'CryptoSwift', '1.8.4'

end

target 'Appcircle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  
  pod 'GoogleMaps', '8.0'
  pod 'SwiftyGif', '5.4.5'
  pod 'SDWebImage', '5.10.0'
  pod 'Firebase/Core', '10.29.0'
  pod 'Firebase/Messaging', '10.29.0'
  pod 'MaterialTextField', '1.0.1'
  pod 'MaterialComponents/TextControls+OutlinedTextFields', '124.2.0'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas', '124.2.0'
  pod 'Firebase/DynamicLinks', '10.29.0'
  pod 'Firebase/RemoteConfig', '10.29.0'
  pod 'MPQRCoreSDK', '2.0.7'
  pod 'AppDynamicsAgent', '2024.12.0'
  pod 'JOSESwift', '3.0.0'
  pod 'AppsFlyerFramework', '6.16.0'
#  pod 'MFSDKHybridKit', '2.7.43'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'lottie-ios', '4.5.2'
  pod 'RiveRuntime','6.11.2'
  pod "RecaptchaEnterprise", "18.6.0"
  
  # Flutter sdk Pods
  #pod 'Flutter', :podspec => '../appcircle-sample-ios/FlutterSDK/Debug/Flutter.podspec' # This pod is for Debug version
  pod 'Flutter', :podspec => '../appcircle-sample-ios/FlutterSDK/Release/Flutter.podspec' # This pod is for Release version

  target 'AppcircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppcircleUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
      end
    end
    
    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end

    framework_paths = [
      "Pods/MorfeusVoiceKit/googleapis.framework/googleapis",
      "Pods/MorfeusVoiceKit/grpc.framework/grpc",
      "Pods/MorfeusVoiceKit/GRPCClient.framework/GRPCClient",
      "Pods/MorfeusVoiceKit/openssl.framework/openssl",
      "Pods/MorfeusVoiceKit/Protobuf.framework/Protobuf",
      "Pods/MorfeusVoiceKit/ProtoRPC.framework/ProtoRPC",
      "Pods/MorfeusVoiceKit/RxLibrary.framework/RxLibrary",
      "Pods/MPQRCoreSDK/Frameworks/MPQRCoreSDK.framework/MPQRCoreSDK",
    ]
    
    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
  end
end
